### ISSUE TITLE
Support ImmutableJS?

### ISSUE THREAD

**Issue by kruyvanna** [gtournie/redux-form-validators#10]
Hi!
Will it works with redux-form immutablejs?

**Comment by gtournie** [comment]
I'm not completely sure but feel free to try and to tell us if it works :)

**Comment by kruyvanna** [comment]
hi, it's not working with ImmutableJs

**Comment by bogdaniy** [comment]
I use redux-form-validators with redux-form/immutable and still, I have not faced with any problems.

**Comment by gtournie** [comment]
@bogdaniy Thanks for the feedback. I'll reopen this thread if someone gives me some code proving it's not working

**Comment by mshick** [comment]
@gtournie https://github.com/gtournie/redux-form-validators/blob/master/src/confirmation.js#L16 will not work with Immutable because `allValues` is an Immutable map, and not a plain JS object.

This situation could easily be handled by testing if `allValues` is an immutable map, and if so, getting the field value by using `allValues.get(field)`.

I also think it would be smart to support `FormSection` field values, by instead doing something like this:

```
allValues.getIn(field.split('.'));
```

And, likewise, supporting those nested values in plain objects via a nested property getter of some sort.

**Comment by mshick** [comment]
I just put together a small PR: https://github.com/gtournie/redux-form-validators/pull/21

**Comment by gtournie** [comment]
should be fixed by v2.2.0
