### ISSUE TITLE
Does redux-form-validators support aync validaiton?

### ISSUE THREAD

**Issue by cythilya** [gtournie/redux-form-validators#54]
Thanks for implement this validatiors, it is great :)

I have a question...during I read this documents, I just found that it supports sync validation. Does t it support aync validaiton? Are there any examples?

**Comment by gtournie** [comment]
redux-form-validators is just a lib of helpers. It's not designed to support sync or async validations, it's redux-form's job.

So, because redux-form support async validations, I guess the answer of your question is yes.
You can easily replace the validate func described in [this example](https://redux-form.com/8.2.0/examples/asyncchangevalidation/) by this one:
```
const validations = {
  username: [required()],
  password: [required()],
}

// Reusable with any other form
const validate = (values) => {
  const errors = {}
  for (let field in validations) {
    let value = values[field]
    errors[field] = validations[field].map(validateField => {
      return validateField(value, values)
    }).find(x => x)
  }
  return errors
}
```

But if your question is more like: Can I pass a `async: true` option to my validator, then the answer is no. It's not possible due to the way redux-form handle validations.
