### ISSUE TITLE
Where can I find the version changelog?

### ISSUE THREAD

**Issue by mrlubos** [gtournie/redux-form-validators#59]
Hey,

I am struggling to find a comprehensive list of changes between releases, could anyone point me to it please?

Thanks!

**Comment by gtournie** [comment]
@mrlubos Sorry, but there is no changelog available. Maybe if you're telling me what you're looking for I can help you out

**Comment by mrlubos** [comment]
@gtournie When there’s a new update to this package, we cannot blindly accept it and update because it might break something. It’s also not feasible to compare source code and try to figure out what new features are available or other changes made. That’s why change logs are useful

**Comment by gtournie** [comment]
@mrlubos that's why they invented semantic versioning, to be sure nothing will break when you update your packages ;) Unless you updated this package to a new major release, you should be fine.
https://docs.npmjs.com/about-semantic-versioning

That said, change logs are still useful. I will think about it in the next updates.

**Comment by mrlubos** [comment]
Thank you @gtournie

**Comment by mplis** [comment]
It's great that you use semantic versioning, but without a changelog, it can be hard to figure out what breaks between major versions. My project is still on v2 and I'd like to upgrade to v3, but I'm not sure what actually broke.

After digging through the [commits](https://github.com/gtournie/redux-form-validators/commit/dbf3747d5ae993c42f53f760b14b9575542d8e40#diff-b9cfc7f2cdf78a7f4b91a753d10865a2), it seems like it was due to changes in how the `url` validator works. Is that correct? Was that the only breaking change?
