### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by amoghpalnitkar** [gtournie/redux-form-validators#8]
When I import any of the validators from redux-form-validators into my component, I get the following error 

Uncaught SyntaxError: Unexpected token import

Which points somewhere here 
```
/*!**********************************************!*\
  !*** ./~/redux-form-validators/src/index.js ***!
  \**********************************************/
/***/ function(module, exports) {

	import absence from './absence'
	import acceptance from './acceptance'
	import addValidator from './add-validator'
	import confirmation from './confirmation'
```

Anyone else facing this issue? I am using CRA, redux form validators version 2.0.0

**Comment by gtournie** [comment]
@amoghpalnitkar Can you give me more details please? Any snippet?
How do you import the validators? The right way is:
```
import { required } from 'redux-form-validators'
```

**Comment by benbarber** [comment]
I am running into the same issue as well while using the validators in a TypeScript project.

Should it not be importing from `dist` rather than using the un-transpiled source directly? 

```
/node_modules/redux-form-validators/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import absence from './absence'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by tmartensen** [comment]
I'm having the same problem when I try to run Jest tests with CRA. I think the problem stems from the `main` entry in `package.json` pointing to `src/index.js` instead of something in the `dist` directory. Since the code is ES6, and Jest excludes transformation of files in `node_modules`, it subsequently blows up with the error @benbarber supplied. I got around it by importing `redux-form-validators/dist/redux-form-validator` or `redux-form-validators/dist/redux-form-validators.min`.
